spring.datasource.url=jdbc:mysql://localhost:3306/university_erp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=unierp_user
spring.datasource.password=Password@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true